/**
 * EMS Telemetry Runner - Server-Side Singleton
 * 
 * This module starts a SINGLE background telemetry loop that advances
 * the EMS simulation independently of any API requests.
 * 
 * CRITICAL: This mirrors real industrial SCADA/EMS behavior where:
 * - RTU/PLC data acquisition runs on fixed intervals
 * - Telemetry is generated by the system, not by UI requests
 * - Multiple clients receive the SAME data stream
 * - Time belongs to the system, not to the UI
 * 
 * ⚠️ ARCHITECTURAL PRINCIPLES:
 * 1. Simulation advances on WALL-CLOCK time (2 second intervals)
 * 2. API calls are READ-ONLY (never mutate state)
 * 3. Frontend polling frequency does NOT affect physics
 * 4. Multiple users see identical synchronized data
 * 5. Server restart = new telemetry session (like real equipment reboot)
 * 
 * This is the ONLY place where advanceEMSSimulation() should be called.
 */

import { advanceEMSSimulation } from './ems-engine';

/**
 * Configuration for telemetry acquisition
 * These values mirror typical industrial SCADA scan rates
 */
const TELEMETRY_CONFIG = {
  /** Telemetry scan interval (ms) - typical RTU/PLC rate */
  SCAN_INTERVAL_MS: 2000,
  
  /** Startup delay to ensure state initialization */
  STARTUP_DELAY_MS: 100,
} as const;

/**
 * Global flag to prevent multiple telemetry loops
 * Essential for serverless/hot-reload environments
 */
let telemetryRunnerActive = false;
let telemetryIntervalId: NodeJS.Timeout | null = null;

/**
 * Start the EMS telemetry acquisition loop
 * 
 * This function should be called ONCE during server startup.
 * It establishes a fixed-rate data acquisition cycle that mimics
 * real industrial control systems.
 * 
 * @returns void
 */
export function startEMSTelemetryRunner(): void {
  // Prevent multiple instances (critical for singleton pattern)
  if (telemetryRunnerActive) {
    console.log('[EMS Runner] Already active. Skipping duplicate start.');
    return;
  }

  console.log('[EMS Runner] ====================================');
  console.log('[EMS Runner] Starting EMS Telemetry Acquisition');
  console.log('[EMS Runner] Mode: Server-Side Background Loop');
  console.log('[EMS Runner] Scan Rate:', TELEMETRY_CONFIG.SCAN_INTERVAL_MS, 'ms');
  console.log('[EMS Runner] ====================================');

  // Mark runner as active
  telemetryRunnerActive = true;

  // Allow slight delay for state initialization
  setTimeout(() => {
    // Perform initial scan
    console.log('[EMS Runner] Initial telemetry scan...');
    try {
      advanceEMSSimulation();
      console.log('[EMS Runner] ✓ Initial scan complete');
    } catch (error) {
      console.error('[EMS Runner] ✗ Initial scan failed:', error);
    }

    // Start periodic telemetry acquisition
    telemetryIntervalId = setInterval(() => {
      try {
        const state = advanceEMSSimulation();
        
        // Log telemetry updates (reduce noise in production)
        if (process.env.NODE_ENV === 'development') {
          console.log(
            `[EMS Runner] Telemetry: ` +
            `Solar=${state.power.solar.toFixed(1)}kW ` +
            `Load=${state.power.load.toFixed(1)}kW ` +
            `Grid=${state.power.grid.toFixed(1)}kW ` +
            `Battery=${state.power.battery.toFixed(1)}kW ` +
            `SOC=${state.kpis.batterySOC.toFixed(1)}%`
          );
        }
      } catch (error) {
        console.error('[EMS Runner] Telemetry scan error:', error);
      }
    }, TELEMETRY_CONFIG.SCAN_INTERVAL_MS);

    console.log('[EMS Runner] ✓ Background telemetry loop started');
  }, TELEMETRY_CONFIG.STARTUP_DELAY_MS);
}

/**
 * Stop the telemetry runner (for testing or shutdown)
 * In production, this would typically run until process termination
 */
export function stopEMSTelemetryRunner(): void {
  if (!telemetryRunnerActive) {
    console.log('[EMS Runner] Not running. Nothing to stop.');
    return;
  }

  console.log('[EMS Runner] Stopping telemetry acquisition...');
  
  if (telemetryIntervalId) {
    clearInterval(telemetryIntervalId);
    telemetryIntervalId = null;
  }
  
  telemetryRunnerActive = false;
  console.log('[EMS Runner] ✓ Telemetry acquisition stopped');
}

/**
 * Check if telemetry runner is active
 */
export function isEMSTelemetryRunnerActive(): boolean {
  return telemetryRunnerActive;
}

/**
 * IMPORTANT: Auto-start on module import
 * 
 * This ensures the telemetry loop begins as soon as the server starts.
 * In Next.js, this happens during:
 * 1. Initial server startup
 * 2. First API route access (lazy initialization)
 * 
 * The singleton pattern prevents duplicate loops even if this module
 * is imported multiple times.
 */
if (typeof window === 'undefined') {
  // Only run on server-side (not in browser)
  startEMSTelemetryRunner();
}
